name: 'dsa'
version: 0.0.1
description: >

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  polymer: 0.16.3+1
  core_elements: 0.7.1+2
  paper_elements: 0.7.1
  http: 0.11.2
  charted:
    git: git@github.com:google/charted.git
transformers:
- polymer:
    entry_points: web/index.html